### ISSUE TITLE
Module compiled

### ISSUE THREAD

**Issue by devlixz** [mancunianetz/iCheckbox#5]
hello, 
how to fix issue " Module compiled with swift 3.0.1 cannot be imported in swift 2.3 " when import iCheckbox, i use manual install by drag the .xcodeproj to my app project. 

thankyou and nice Lib.

**Comment by mancunianetz** [comment]
Hi @devlixz , 

There are 2 ways of solving this:

1) Convert your project to use latest Swift version. Depend on your project size this can be a pain.
2) For `iCheckbox` project, change `Use Legacy Swift Language Version` to `YES`.  This will force you to do a lot of fixes to match older Swift version syntax.

Sadly, I don't have plans to support older Swift versions, and as far as I know near future Xcode releases will force you to use only Swift 3.
