### ISSUE TITLE
Can we Customise the Font For the CheckBox Title ?

### ISSUE THREAD

**Issue by charmiturakhia** [mancunianetz/iCheckbox#6]

**Comment by mancunianetz** [comment]
Seems you've fixed this. In any case, you can add the following method in `iCheckbox` class, 

```
    func setFont(font: UIFont) {
        self.titleLabel?.font = font
    }
```

**Comment by charmiturakhia** [comment]
Thanks for immediate response.. and yes I have fixed it. Awesome icheckbox.
Really help ful
