### ISSUE TITLE
How to add constraints to checkboxes?

### ISSUE THREAD

**Issue by zhanswift** [mancunianetz/iCheckbox#7]
I need checkboxes in a certain place. How to do?

**Comment by mancunianetz** [comment]
Hi @zhanswift 
Sorry for late reply!

In case you've still not figure it out, look at   `witCanvas` parameter from `iCheckboxBuilder` init method
`let checkboxBuilder = iCheckboxBuilder(withCanvas: self.view, andConfig: checkboxBuilderConfig)
`
The view passed should be container of the checkboxs, so the only thing you need change checkboxes position is to play with container position itself.

I know it's not the best way to deal with it, but it's the only way to do it fast.
